---
- include: create_groups.yml

- name: Apply the db-server role to DB server
  hosts: db-server
  become: yes
  pre_tasks:
    - name: Show hadoop-cluster info
      debug: var=hostvars[inventory_hostname]
      when: debug

    - name: include hortonworks vars
      include_vars: group_vars/db-server
  
  roles:
    - db-server

- name: Apply the ambari-agent role to all nodes
  hosts: hadoop-cluster
  any_errors_fatal: true
  become: yes
  pre_tasks:
    - name: Show hadoop-cluster info
      debug: var=hostvars[inventory_hostname]
      when: debug

    - name: include hortonworks vars
      include_vars: group_vars/hortonworks

  roles:
    - ambari-agent

- name: Apply the ambari-server role to ambari-node group
  hosts: ambari-node
  become: yes
  pre_tasks:
    - name: include hortonworks vars
      include_vars: group_vars/hortonworks

  roles:
    - ambari-server
  post_tasks:
    - name: Cleanup the temporary files
      file: path={{ item }} state=absent
      with_items:
        - /tmp/cluster_blueprint
        - /tmp/cluster_template
        - /tmp/alert_targets
        - /tmp/hdprepo
  tags:
    - ambari-server-only
